### PR TITLE
Add support for multiple ignore strings

### PR DESCRIPTION
**Pull request by ghost**
Useful to discern between a snippet that won't compile and a code
fragment, by using separate comments for each:

```
md2src README.md -i '// ⚠️ won\'t compile' -i '// 🚧 fragment'
```

Emoji should be OK as code comments as well.

Please let me know if this looks acceptable,
Thanks!

### CODE REVIEW

**Comment by AlexanderWillner** [comment]
very good

**Comment by ghost** [comment]
Example with emoji-only: https://github.com/Dhghomon/easy_rust/issues/38#issuecomment-665593347

**Comment by Dhghomon** [comment]
Okay, merging this now. Thanks!

**Comment by Dhghomon** [comment]
Oh wait, this is @AlexanderWillner's page. I'll merge when I get the PR on Easy Rust then!

(Let me know if I'm doing something wrong - still newish to GitHub)

**Comment by AlexanderWillner** [comment]
fyi: released md2src version 1.1.0, which includes your change

**Pull request merged**
